"""Dashboard API response schemas."""

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


# ─── Overview ──────────────────────────────────────────────────

class DashboardOverview(BaseModel):
    """Aggregate statistics for the security dashboard."""

    total_requests: int
    suspicious_requests: int
    decoy_redirects: int
    active_alerts: int
    average_risk_score: float = Field(ge=0, le=100)


# ─── Alerts ────────────────────────────────────────────────────

class AlertSeverity(str, Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class AlertRecord(BaseModel):
    """Single security alert."""

    alert_id: str
    severity: AlertSeverity
    title: str
    description: str
    recommended_action: str
    created_at: datetime


# ─── Decoy Status ──────────────────────────────────────────────

class DecoyStatus(BaseModel):
    """Current state of decoy environments."""

    active_decoys: int
    fake_endpoints: list[str]
    captured_interactions: int
    last_decoy_trigger: datetime | None = None


# ─── Decoy Response ────────────────────────────────────────────

class DecoyResponseRequest(BaseModel):
    """Input for generating a decoy response."""

    path: str
    decoy_type: str = Field(
        default="auto",
        description="Type of decoy: auto, login, admin, config, token, database",
    )


class DecoyResponse(BaseModel):
    """Safe fake response generated by the decoy engine."""

    decoy_type: str
    status_code: int
    body: dict
    note: str = "This is a MIRAGE demo decoy response. No real data is included."
