"""Dashboard API response schemas."""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field

from app.schemas.honeytoken import HoneytokenHit


# ─── Overview ──────────────────────────────────────────────────

class DashboardOverview(BaseModel):
    """Aggregate statistics for the security dashboard."""

    total_requests: int
    suspicious_requests: int
    decoy_redirects: int
    active_alerts: int
    average_risk_score: float = Field(ge=0, le=100)


class TrainingDataSummary(BaseModel):
    """Readiness summary for analyst-labeled model training data."""

    labeled_rows: int = Field(ge=0)
    exportable_rows: int = Field(ge=0)
    minimum_rows: int = Field(ge=1)
    minimum_rows_per_class: int = Field(ge=1)
    normal_rows: int = Field(ge=0)
    suspicious_rows: int = Field(ge=0)
    has_both_classes: bool
    has_minimum_class_rows: bool
    ready_for_training: bool
    analyst_labels: dict[str, int]


class MLShadowStatus(BaseModel):
    """Operator-facing status for optional ML shadow scoring."""

    mode: Literal["disabled", "missing", "invalid", "shadow_ready"]
    artifact: str | None = None
    shadow_ready: bool
    monitor_threshold: float = Field(ge=0, le=1)
    redirect_threshold: float = Field(ge=0, le=1)
    metrics: dict[str, float | int]
    blockers: list[str]
    warnings: list[str]


class HoneytokenSummary(BaseModel):
    """Recent honeytoken activity for the dashboard."""

    total_hits: int = Field(ge=0)
    hits: list[HoneytokenHit]


# ─── Alerts ────────────────────────────────────────────────────

class AlertSeverity(str, Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class AlertRecord(BaseModel):
    """Single security alert."""

    alert_id: str
    severity: AlertSeverity
    title: str
    description: str
    recommended_action: str
    created_at: datetime


# ─── Decoy Status ──────────────────────────────────────────────

class DecoyStatus(BaseModel):
    """Current state of decoy environments."""

    active_decoys: int
    fake_endpoints: list[str]
    captured_interactions: int
    last_decoy_trigger: datetime | None = None


# ─── Decoy Response ────────────────────────────────────────────

class DecoyResponseRequest(BaseModel):
    """Input for generating a decoy response."""

    path: str = Field(min_length=1, max_length=2048, pattern=r"^/")
    decoy_type: Literal["auto", "login", "admin", "config", "token", "database"] = Field(
        default="auto",
        description="Type of decoy: auto, login, admin, config, token, database",
    )


class DecoyResponse(BaseModel):
    """Safe fake response generated by the decoy engine."""

    decoy_type: str
    status_code: int
    body: dict
    note: str = "This is a MIRAGE demo decoy response. No real data is included."
