"""Dashboard API response schemas."""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Literal

from pydantic import BaseModel, Field

from app.schemas.actor import ActorCase, ActorCaseWorkflow, ActorCluster, ActorProfile
from app.schemas.honeytoken import HoneytokenHit


# ─── Overview ──────────────────────────────────────────────────

class DashboardOverview(BaseModel):
    """Aggregate statistics for the security dashboard."""

    total_requests: int
    suspicious_requests: int
    decoy_redirects: int
    active_alerts: int
    average_risk_score: float = Field(ge=0, le=100)


class TrainingDataSummary(BaseModel):
    """Readiness summary for analyst-labeled model training data."""

    labeled_rows: int = Field(ge=0)
    exportable_rows: int = Field(ge=0)
    minimum_rows: int = Field(ge=1)
    minimum_rows_per_class: int = Field(ge=1)
    normal_rows: int = Field(ge=0)
    suspicious_rows: int = Field(ge=0)
    has_both_classes: bool
    has_minimum_class_rows: bool
    ready_for_training: bool
    analyst_labels: dict[str, int]


class MLShadowStatus(BaseModel):
    """Operator-facing status for optional ML shadow scoring."""

    mode: Literal["disabled", "missing", "invalid", "shadow_ready"]
    artifact: str | None = None
    shadow_ready: bool
    monitor_threshold: float = Field(ge=0, le=1)
    redirect_threshold: float = Field(ge=0, le=1)
    metrics: dict[str, float | int]
    blockers: list[str]
    warnings: list[str]


class MLShadowDecisionBreakdown(BaseModel):
    """Decision counts observed in model-only shadow scores."""

    allow: int = Field(ge=0)
    monitor: int = Field(ge=0)
    redirect_to_decoy: int = Field(ge=0)


class MLShadowSummary(BaseModel):
    """Recent model-only decision agreement summary."""

    inspected_events: int = Field(ge=0)
    shadow_events: int = Field(ge=0)
    agreements: int = Field(ge=0)
    disagreements: int = Field(ge=0)
    agreement_rate: float = Field(ge=0, le=1)
    average_probability: float = Field(ge=0, le=1)
    average_score: float = Field(ge=0, le=100)
    live_decisions: MLShadowDecisionBreakdown
    shadow_decisions: MLShadowDecisionBreakdown


class HoneytokenSummary(BaseModel):
    """Recent honeytoken activity for the dashboard."""

    total_hits: int = Field(ge=0)
    hits: list[HoneytokenHit]


class ActorProfileSummary(BaseModel):
    """Recent actor profiles built from threat fingerprints."""

    total_actors: int = Field(ge=0)
    profiles: list[ActorProfile]


class ActorClusterSummary(BaseModel):
    """Lightweight actor clusters for threat-hunting triage."""

    total_clusters: int = Field(ge=0)
    clusters: list[ActorCluster]


class ActorCaseSummary(BaseModel):
    """Recommended actor cases for analyst triage."""

    total_cases: int = Field(ge=0)
    cases: list[ActorCase]


class ActorCaseWorkflowSummary(BaseModel):
    """Persisted actor case workflows for analyst triage."""

    total_cases: int = Field(ge=0)
    cases: list[ActorCaseWorkflow]


# ─── Alerts ────────────────────────────────────────────────────

class AlertSeverity(str, Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class AlertRecord(BaseModel):
    """Single security alert."""

    alert_id: str
    severity: AlertSeverity
    title: str
    description: str
    recommended_action: str
    created_at: datetime


# ─── Decoy Status ──────────────────────────────────────────────

class DecoyStatus(BaseModel):
    """Current state of decoy environments."""

    active_decoys: int
    fake_endpoints: list[str]
    captured_interactions: int
    last_decoy_trigger: datetime | None = None


# ─── Decoy Response ────────────────────────────────────────────

class DecoyResponseRequest(BaseModel):
    """Input for generating a decoy response."""

    path: str = Field(min_length=1, max_length=2048, pattern=r"^/")
    decoy_type: Literal["auto", "login", "admin", "config", "token", "database"] = Field(
        default="auto",
        description="Type of decoy: auto, login, admin, config, token, database",
    )
    actor_hint: str = Field(
        default="",
        max_length=128,
        description="Optional actor/fingerprint hint used for synthetic token assignment",
    )
    risk_score: float | None = Field(
        default=None,
        ge=0,
        le=100,
        description="Optional current risk score used to select a decoy variant",
    )


class DecoyResponse(BaseModel):
    """Safe fake response generated by the decoy engine."""

    decoy_type: str
    variant: str = "standard"
    status_code: int
    body: dict
    note: str = "This is a MIRAGE demo decoy response. No real data is included."
